# Generated by Django 5.2.16 on 2026-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("resident", "Resident"),
                            ("guardian", "Guardian"),
                            ("volunteer", "Volunteer"),
                            ("security", "Security"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
